name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install asdf-vm
        uses: asdf-vm/actions/install@v3

      - name: Install asdf plugin
        run: |
          ln -s "$(pwd)" ~/.asdf/plugins/awfy
          ~/.asdf/bin/asdf install awfy latest:graaljs
          ~/.asdf/bin/asdf install awfy latest:pharo
          ~/.asdf/bin/asdf install awfy latest:squeak
