name: Release

# on:
#   push:
#     branches:
#       - main

# Only run this one manually, because it doesn't work in this setup
on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: simple
